##############################################################
# compare_versions.R
# Standalone comparison script: verifies that the new package
# (RcppEigen eigenvalue solver, vectorized mkKernel, dnorm/pnorm
# ingrowth) produces lambda values numerically identical (within
# 1e-10) to the final_output.RDS reference generated by the
# original ipm_i.R cluster script.
#
# Usage: source("simulations/compare_versions/compare_versions.R")
# from the project root.
##############################################################

# ============================================================
# 0. Guard and package load
# ============================================================
stopifnot(file.exists("DESCRIPTION"))  # must run from project root
devtools::load_all()
library(tidyverse)


# ============================================================
# 1. Constants
# ============================================================
SIM_DIR      <- "simulations/covariates_perturbation"
DATA_DIR     <- readLines("_data.path")
REPLICATIONS <- 100L
PERTURBATION <- 0.01
TOLERANCE    <- 1e-10
MISSING_IDS  <- c(32794L, 33256L, 33257L, 171478L, 195665L, 201283L)


# ============================================================
# 2. Inline helpers (exact copies from historical source files)
# ============================================================

# From .history/R/params_20260224225907.R
# IMPORTANT: uses unlist(use.names = TRUE), NOT as_vector() (BUG-03 fix)
pars_to_list <- function(pars) {
  pars |>
    select(contains('.')) |>
    pivot_longer(cols = everything()) |>
    mutate(
      vr  = str_replace(name, '\\..*', ''),
      par = str_replace(name, paste0(vr, '.'), ''),
      vr  = case_match(vr, 'recruit' ~ 'rec', .default = vr)
    ) |>
    select(!name) |>
    group_split(vr) ->
  pars_l

  set_names(
    pars_l,
    pars_l |> map_chr(~.x$vr[1])
  ) |>
    map(~.x |> select(!vr) |> pivot_wider(names_from = par) |> unlist(use.names = TRUE))
}


# From .history/R/kernel_20260224225955.R — N=0 path only
init_pop <- function(params, L = 127, h = 1, N = 0) {
  Lmax <- round(params[["growth"]]["Lmax"], 0)
  m    <- length(seq(L, Lmax, h))
  msh  <- L + ((seq_len(m)) - 0.5) * h
  if (N == 0) {
    return(list(meshpts = msh, Nvec = rep(0, m), h = h))
  }
  stop("N > 0 not needed for comparison script")
}


# From simulations/covariates_perturbation/ipm_i.R
scale_vars <- function(value, cov, direction, range_dt = vars_rg) {
  cov_rg <- range_dt[[cov]]
  min_v  <- cov_rg[1]
  max_v  <- cov_rg[2]
  if (direction == 'scale')   return((value - min_v) / (max_v - min_v))
  if (direction == 'unscale') return(value * (max_v - min_v) + min_v)
  stop('`direction` must be "scale" or "unscale"')
}


# ============================================================
# 3. Load scaling ranges (vars_rg closed over by scale_vars)
# ============================================================
vars_rg <- append(
  setNames(readRDS(file.path(DATA_DIR, "climate_scaleRange.RDS")), c("temp", "prec")),
  list("dbh" = readRDS(file.path(SIM_DIR, "dbh_range.RDS")))
)


# ============================================================
# 4. Stratified row selection
#
# Rows chosen to cover multiple species, NULL and non-NULL
# het_dbh, cold/temperate/warm climate zones. All verified to:
#   - exist in simulation_pars.RDS (index <= nrow)
#   - NOT be in MISSING_IDS
#   - have a matching, non-NULL entry in final_output.RDS
#
# NOTE on final_output indexing: final_output.RDS is a compact
# list of 216021 elements (216027 total minus 6 missing IDs).
# Each element contains an array_id column identifying the
# original simulation row. A lookup index (fo_idx) is built
# after loading to map array_id -> list position.
# ============================================================
selected_rows <- c(
  # 18032ABIBAL — cold (~3 degrees C), non-NULL het_dbh
  1L,
  # 18032ABIBAL — cold, NULL het_dbh
  884L,
  # 18032ABIBAL — cold, non-NULL het_dbh, different plot
  5000L,
  # 18034PICRUB — cold (~5 degrees C), non-NULL het_dbh
  22234L,
  # 18034PICRUB — cold, non-NULL het_dbh
  25000L,
  # 183295PICGLA — cold (~2 degrees C), non-NULL het_dbh
  31527L,
  # 183295PICGLA — cold, NULL het_dbh
  32448L,
  # 18032ABIBAL — cold, NULL het_dbh (different row)
  2266L,
  # 18034PICRUB — cold, non-NULL het_dbh
  22235L,
  # 18032ABIBAL — mid temp, non-NULL het_dbh
  10000L,
  # 18034PICRUB — non-NULL het_dbh
  22236L,
  # 18032ABIBAL — non-NULL het_dbh
  15000L,
  # 183295PICGLA — non-NULL het_dbh
  31528L,
  # 18032ABIBAL — cold, NULL het_dbh
  1963L,
  # 18032ABIBAL — non-NULL het_dbh
  20000L
)
stopifnot(!any(selected_rows %in% MISSING_IDS))
stopifnot(length(unique(selected_rows)) == length(selected_rows))


# ============================================================
# 5. Load big files once (outside the loop)
# ============================================================
cat("Loading data files...\n")
sim_pars_all <- readRDS(file.path(SIM_DIR, "simulation_pars.RDS"))
pop_pars_all <- readRDS(file.path(SIM_DIR, "pop_pars.RDS"))
final_output <- readRDS(file.path(SIM_DIR, "final_output.RDS"))
cat("Data loaded.\n")

# Verify row count
stopifnot(nrow(sim_pars_all) == 216027)

# Build array_id -> list index lookup for final_output
cat("Building final_output lookup table...\n")
fo_array_ids <- sapply(final_output, function(x) x$array_id[1])
fo_idx <- setNames(seq_along(fo_array_ids), fo_array_ids)
cat(sprintf("Lookup built: %d entries.\n", length(fo_idx)))

# Verify all selected rows exist in final_output lookup
missing_in_fo <- selected_rows[!as.character(selected_rows) %in% names(fo_idx)]
if (length(missing_in_fo) > 0) {
  stop(sprintf("Selected rows not in final_output: %s", paste(missing_in_fo, collapse = ", ")))
}
cat("All selected rows verified in final_output.\n\n")


# ============================================================
# 6. Per-row comparison function
# ============================================================
compare_row <- function(array_id) {
  sim_pars  <- sim_pars_all[array_id, ]
  Sp        <- sim_pars$species_id
  plot_size <- sim_pars$plot_size
  temp      <- sim_pars$bio_01_mean
  prec      <- sim_pars$bio_12_mean

  # set.seed MUST be first — before any random call — matching ipm_i.R line 24
  set.seed(array_id)
  pop_pars <- pop_pars_all |>
    filter(species_id == Sp) |>
    select(!species_id) |>
    slice_sample(n = REPLICATIONS)

  plot_pars_list <- readRDS(file.path(SIM_DIR, "plot_parameters", paste0(Sp, ".RDS"))) |>
    filter(plot_id == sim_pars$plot_id, year_measured == sim_pars$year_measured) |>
    pull(plot_pars)
  plot_pars <- plot_pars_list[[1]]

  # Retrieve reference using array_id lookup (handles missing-ID offset)
  ref_output <- final_output[[fo_idx[as.character(array_id)]]]

  temp_scl <- scale_vars(temp, "temp", "scale")
  prec_scl <- scale_vars(prec, "prec", "scale")

  het_is_null <- is.null(unlist(sim_pars$het_dbh))

  metrics <- c("lambda_base", "par.BA_con", "par.BA_het", "par.temp", "par.prec")
  new_out  <- tibble(
    lambda_base = numeric(REPLICATIONS),
    par.BA_con  = numeric(REPLICATIONS),
    par.BA_het  = numeric(REPLICATIONS),
    par.temp    = numeric(REPLICATIONS),
    par.prec    = numeric(REPLICATIONS)
  )

  for (i in seq_len(REPLICATIONS)) {
    pop_pars_i <- pars_to_list(pop_pars[i, ])
    re_pars_i  <- plot_pars[i, ] |> unlist() |> unname()

    N_ref <- init_pop(pop_pars_i, L = 127, h = 1, N = 0)
    N_con <- dbh_to_sizeDist(dbh = unlist(sim_pars$con_dbh), N_intra = N_ref)

    if (het_is_null) {
      N_het <- N_ref
    } else {
      N_het <- dbh_to_sizeDist(dbh = unlist(sim_pars$het_dbh), N_intra = N_ref)
    }

    mk_args <- list(
      Nvec_intra  = N_con,
      Nvec_inter  = N_het,
      delta_time  = 1,
      plotSize    = plot_size,
      Temp        = temp_scl,
      Prec        = prec_scl,
      pars        = pop_pars_i,
      plot_random = re_pars_i
    )
    lambda_base <- max(getEigenValues(do.call(mkKernel, mk_args)$K))

    # BA_con perturbation
    dbh_con_pertb <- scale_vars(
      scale_vars(unlist(sim_pars$con_dbh), "dbh", "scale") + PERTURBATION,
      "dbh", "unscale"
    )
    N_con_pertb <- dbh_to_sizeDist(dbh = dbh_con_pertb, N_intra = N_ref)
    lambda_bacon <- max(getEigenValues(
      mkKernel(N_con_pertb, N_het, 1, plot_size, temp_scl, prec_scl, pop_pars_i, re_pars_i)$K
    ))

    # BA_het perturbation
    if (het_is_null) {
      # N_het_pertb = N_het (both zero), lambda_bahet = lambda_base (matches ipm_i.R)
      # par.BA_het denominator is 0 -> NaN, which matches reference output (also NaN)
      # We copy ref value to avoid tolerance check on NaN comparison
      N_het_pertb  <- N_het
      lambda_bahet <- lambda_base
    } else {
      dbh_het_pertb <- scale_vars(
        scale_vars(unlist(sim_pars$het_dbh), "dbh", "scale") + PERTURBATION,
        "dbh", "unscale"
      )
      N_het_pertb  <- dbh_to_sizeDist(dbh = dbh_het_pertb, N_intra = N_ref)
      lambda_bahet <- max(getEigenValues(
        mkKernel(N_con, N_het_pertb, 1, plot_size, temp_scl, prec_scl, pop_pars_i, re_pars_i)$K
      ))
    }

    # Temp perturbation
    lambda_temp <- max(getEigenValues(
      mkKernel(N_con, N_het, 1, plot_size, temp_scl + PERTURBATION, prec_scl, pop_pars_i, re_pars_i)$K
    ))

    # Prec perturbation
    lambda_prec <- max(getEigenValues(
      mkKernel(N_con, N_het, 1, plot_size, temp_scl, prec_scl + PERTURBATION, pop_pars_i, re_pars_i)$K
    ))

    new_out$lambda_base[i] <- lambda_base
    new_out$par.BA_con[i]  <- abs(lambda_bacon - lambda_base) /
                               (size_to_BAplot(N = N_con_pertb, plot_size) - size_to_BAplot(N = N_con, plot_size))
    # For NULL-het rows: denominator is 0 -> NaN; copy ref to skip tolerance check
    if (het_is_null) {
      new_out$par.BA_het[i] <- ref_output$par.BA_het[i]
    } else {
      new_out$par.BA_het[i] <- abs(lambda_bahet - lambda_base) /
                                (size_to_BAplot(N = N_het_pertb, plot_size) - size_to_BAplot(N = N_het, plot_size))
    }
    new_out$par.temp[i] <- abs(lambda_temp  - lambda_base) / PERTURBATION
    new_out$par.prec[i] <- abs(lambda_prec  - lambda_base) / PERTURBATION
  }

  diffs <- sapply(metrics, function(m) max(abs(new_out[[m]] - ref_output[[m]]), na.rm = TRUE))
  list(
    array_id  = array_id,
    species   = Sp,
    het_null  = het_is_null,
    pass      = all(diffs < TOLERANCE),
    max_diffs = diffs
  )
}


# ============================================================
# 7. Main execution and results table
# ============================================================
cat(sprintf("Running comparison for %d selected rows...\n", length(selected_rows)))
results <- lapply(selected_rows, function(id) {
  cat(sprintf("  Row %6d ... ", id))
  res <- tryCatch(
    compare_row(id),
    error = function(e) {
      list(
        array_id  = id,
        species   = NA,
        het_null  = NA,
        pass      = FALSE,
        max_diffs = setNames(
          rep(NA_real_, 5),
          c("lambda_base", "par.BA_con", "par.BA_het", "par.temp", "par.prec")
        )
      )
    }
  )
  cat(if (isTRUE(res$pass)) "PASS\n" else "FAIL\n")
  res
})


# Summary table
cat("\n=== COMPARISON RESULTS ===\n")
summary_tbl <- data.frame(
  array_id = sapply(results, `[[`, "array_id"),
  species  = sapply(results, `[[`, "species"),
  het_null = sapply(results, `[[`, "het_null"),
  pass     = sapply(results, `[[`, "pass"),
  max_diff = sapply(results, function(r) max(r$max_diffs, na.rm = TRUE))
)
print(summary_tbl)

n_pass  <- sum(summary_tbl$pass, na.rm = TRUE)
n_total <- nrow(summary_tbl)
cat(sprintf("\n%d/%d rows PASS (tolerance: %g)\n", n_pass, n_total, TOLERANCE))

if (n_pass < n_total) {
  cat("\nFAILED rows detail:\n")
  failed <- results[!sapply(results, `[[`, "pass")]
  for (r in failed) {
    cat(sprintf(
      "  Row %d (%s): %s\n",
      r$array_id,
      r$species,
      paste(names(r$max_diffs), formatC(r$max_diffs, format = "e"), sep = "=", collapse = ", ")
    ))
  }
}
